### ISSUE TITLE
"HTTP Error 502.5 - Process Failure" asp.net core error in Azure

### ISSUE THREAD

**Issue by ardacetinkaya** [aspnet/IISIntegration#252]
Hi;
I just deployed my asp.net core app to azure which I developed in mac os x. It is successfully build and run on my local environment.

But when I browse the app on Azure site, I got the following error.

![screen shot 2016-08-17 at 3 58 31 pm](https://cloud.githubusercontent.com/assets/4550197/17737018/80d6113a-6493-11e6-8ed7-b265267159d6.png)

I checked the link in error https://docs.asp.net/en/latest/publishing/iis.html#common-errors for some info but could not link with my issue.

Also when I check Azure logs, in Application Logs, I have

> HTTP Error 502.5 - Bad Gateway
> The specified CGI application encountered an error and the server terminated the process.
> Most likely causes:
> The CGI application did not return a valid set of HTTP errors.A server acting as a proxy or gateway was unable to process the request due to an error in a parent gateway.

Also some additional info in Application Logs

> Requested URL--http://maping:80/ (this line seemed interesting to me)
> Physical Path--D:\home\site\wwwroot

My web.config is like below;
```xml
<?xml version="1.0"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>

And finally my project.json file;

`
{
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0"
  },
  "frameworks": {
    "netcoreapp1.0": {}
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },
}`


Any idea?

I have also below properties for project.json

 "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }

**Comment by ardacetinkaya** [comment]
I have also below properties for project.json

 ```
 "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }
```

**Comment by Tratcher** [comment]
Check your event logs in D:\home\Logfiles\EventLog.xml
RE: https://blogs.msdn.microsoft.com/puneetgupta/2014/09/24/azure-website-siteextension-to-view-eventlogs/

**Comment by muratg** [comment]
@ardacetinkaya Can you also share the `web.config` file in your publish path?  `publish-iis` modifies that file (or is supposed to modify it)

**Comment by ardacetinkaya** [comment]
@muratg you can close this issue,after some check I found the problem which is related with my configuration.

**Comment by iwasdavid** [comment]
@ardacetinkaya what was the issue with your configuration? I'm having the same problem.

**Comment by ZombiesWithCoffee** [comment]
I upgraded to asp.net core 1.0.1 today and this started appearing for me.

I'd assume that it might have something to do with the project.json file.  I wonder if we need to add a new line to the 'runtimes' section.

    "runtimes": {
        "win10-x64": {}
    },

**Comment by ardacetinkaya** [comment]
@iwasdavid my problem is about application path that I do the deployment. There was wrong binaries.

@ZombiesWithCoffee I am not sure but .NET Core in Azure might be still 1.0.0

**Comment by muratg** [comment]
@ZombiesWithCoffee if @ardacetinkaya's comment doesn't help, please share your web.config (in the publish path).

**Comment by ZombiesWithCoffee** [comment]
Will do muratg,

I've been posting to my Azure website nearly daily with updates without any issue.  Once I upgraded to 1.0.1 this morning, I now only get **HTTP Error 502.5 - Process Failure**.  Uninstalling only made things worse.

web.config

'<?xml version="1.0" encoding="utf-8"?>
<configuration>

  

  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
  </system.webServer>
</configuration>
'

project.json
`{
    "userSecretsId": "aspnet-SafeInvestigation-a7ae238a-cbe6-407a-b9e2-eb10cf893b2c",

    "dependencies": {
        "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
        "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
        "Microsoft.AspNetCore.Diagnostics": "1.0.0",
        "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
        "Microsoft.AspNetCore.Razor.Tools": {
            "version": "1.0.0-preview2-final",
            "type": "build"
        },
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
        "Microsoft.AspNetCore.StaticFiles": "1.0.0",
        "Microsoft.EntityFrameworkCore.Tools": {
            "version": "1.0.0-preview2-final",
            "type": "build"
        },
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
        "Microsoft.Extensions.Logging": "1.0.0",
        "Microsoft.Extensions.Logging.Console": "1.0.0",
        "Microsoft.Extensions.Logging.Debug": "1.0.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
        "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
            "version": "1.0.0-preview2-final",
            "type": "build"
        },
        "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
            "version": "1.0.0-preview2-final",
            "type": "build"
        },
        "Microsoft.AspNetCore.Session": "1.0.0",
        "LinqKit.Microsoft.EntityFrameworkCore": "1.0.5",
        "Microsoft.AspNetCore.Mvc": "1.0.1",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.1",
        "Microsoft.NETCore.App": "1.0.1"
    },

    "tools": {
        "BundlerMinifier.Core": "2.2.281",
        "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
        "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
        "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
            "version": "1.0.0-preview2-final",
            "imports": [
                "portable-net45+win8"
            ]
        }
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "dotnet5.6",
                "portable-net45+win8"
            ]
        }
    },

    "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
    },

    "runtimeOptions": {
        "configProperties": {
            "System.GC.Server": true
        }
    },

    "publishOptions": {
        "include": [
            "wwwroot",
            "Views",
            "Areas/**/Views",
            "appsettings.json",
            "web.config"
        ]
    },

    "runtimes": {
        "win10-x64": {}
    },

    "scripts": {
        "prepublish": [ "bower install", "dotnet bundle" ],
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
    }
}
`

**Comment by moozzyk** [comment]
Either you showed web.config before publishing or publish-iis failed (should print an error). These:
`processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%"` should be replaced with the actual values.

**Comment by ZombiesWithCoffee** [comment]
You're right.  I showed the 'before' web.config - I was sitting here editing my post at least 20 times to get the formatting right.

Here is the post process web.config

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\SafeInvestigation.exe" arguments="" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
`

**Comment by moozzyk** [comment]
This config looks good. Check the Azure equivalent of event log. Also, enable std out logging (by flipping `stdoutLogEnabled` to `true` and check the contents of the stoud file. You should get some details as to what is happening.

**Comment by ZombiesWithCoffee** [comment]
Excellent suggestion on the stdoutLogEnabled.

I'm finally seeing *something*.

         fail: Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[1]
         An exception occurred in the database while iterating the results of a query.
      System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
         at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)

**Comment by moozzyk** [comment]
I wonder if it is a bitness issue. @divega will know more.

**Comment by muratg** [comment]
Yeah I suspect @moozzyk is correct. Azure Websites do not support 64 bit apps currently. I recommend trying out 32 bits

**Comment by ZombiesWithCoffee** [comment]
Err, I've been posting my site on Azure since asp.net core went live.  Why does an upgrade to 1.0.1 break it?

**Comment by ZombiesWithCoffee** [comment]
So @moozzyk or @muratg, does anyone have any suggestions on how to get my website back up and running again?  This version 1.0.1 is an absolute development killer.

**Comment by divega** [comment]
@saurabh500 see https://github.com/aspnet/IISIntegration/issues/252#issuecomment-247686538. Any changes in SqlClient in 1.0.1 that could cause issues with loading sni.dll again?

**Comment by saurabh500** [comment]
@divega No changes from Data team for 1.0.1 to SqlClient

**Comment by divega** [comment]
Thanks @saurabh500. @muratg should we reactivate this or create a new issue? Also, do you think this could be an issue with the shared framework?

It has been reported also at https://blogs.msdn.microsoft.com/webdev/2016/09/13/asp-net-core-sept-2016-patch/#comments

**Comment by ZombiesWithCoffee** [comment]
Could it have something to do with the new "runtimes" requirement in project.json?  I had to add it just to get 1.0.1 to run locally.  Is there a different runtime for Azure?

        "runtimes": {
            "win10-x64": {}
        },

When I browse my website on Server Explorer, I see 

        /Files/runtimes/win
        /Files/runtimes/win7-x64
        /Files/runtimes/win7-x86

**Comment by ysilvestrov** [comment]
I have the same issue; does anyone have any suggestions to fix it?

**Comment by ZombiesWithCoffee** [comment]
I'm trying something out, I hope to let you know in 30 more mins.

**Comment by ZombiesWithCoffee** [comment]
I finally figured out the issue!  When you upgraded your app, your 'Microsoft.NETCoreApp' setting in your project.json was changed to

`        "Microsoft.NETCore.App": "1.0.1",`

This generated an error message that told us to change the project file to include a runtime section.  So I changed mine to this after reading several posts.

`"runtimes": {
    "win10-x64": {}
},`

The **correct** answer was to fix the setting by fixing the App 'type'.

`        "Microsoft.NETCore.App": {
            "version": "1.0.1",
            "type": "platform"
        },`

**Comment by ysilvestrov** [comment]
@ZombiesWithCoffee Thanks, it works now!

**Comment by dcarl1** [comment]
@ZombiesWithCoffee I'm having the exact same issue except I'm using NET46 instead of ASPNET Core so I don't have the "Microsoft.NETCore.App" dependency. 

Also, I've turned on stdoutlogging however the files are empty. Web.config looks fine:



`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\WebUI-New.exe" arguments="" stdoutLogEnabled="false" forwardWindowsAuthToken="false" stdoutLogFile="\\?\%home%\LogFiles\stdout" />
    <staticContent>
      <remove fileExtension=".ts" />
      <mimeMap fileExtension=".ts" mimeType="application/x-typescript" />
      <remove fileExtension=".tsx" />
      <mimeMap fileExtension=".tsx" mimeType="text/plain" />
    </staticContent>
  </system.webServer>
</configuration>
`

**Project.json**:

`{
    "dependencies": {
        "Microsoft.AspNetCore.ReactServices": "1.0.0-*",
        "Microsoft.AspNetCore.Diagnostics": "1.0.0",
        "Microsoft.AspNetCore.Razor.Tools": {
            "version": "1.0.0-preview2-final",
            "type": "build"
        },
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
        "Microsoft.AspNetCore.StaticFiles": "1.0.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Configuration.CommandLine": "1.0.0",
        "Microsoft.Extensions.Logging": "1.0.0",
        "Microsoft.Extensions.Logging.Console": "1.0.0",
        "Microsoft.Extensions.Logging.Debug": "1.0.0",
        "EntityFramework": "6.1.3",
        "Migrator.EF6.Tools": {
            "version": "1.0.1",
            "type": "build"
        },
        "System.Linq": "4.1.0",
        "Newtonsoft.Json": "9.0.1",
        "Microsoft.Azure.KeyVault.Core": "1.0.0",
        "Microsoft.AspNetCore.Identity": "1.0.0",
        "MR.AspNet.Identity.EntityFramework6": "2.0.0",
        "CommonServiceLocator": "1.3.0",
        "Microsoft.Extensions.Options": "1.0.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
        "Microsoft.Bcl.Build": "1.0.21",
        "Autofac.Extensions.DependencyInjection": "4.0.0",
        "Autofac.Extras.CommonServiceLocator": "4.0.0",
        "Microsoft.Bcl": "1.1.10",
        "ISO3166": "1.0.1",
        "WindowsAzure.Storage": "7.2.1",
        "Hangfire.Core": "1.6.4",
        "Microsoft.AspNetCore.Mvc": "1.0.1",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
        "Hangfire.AspNetCore": "1.6.4",
        "Hangfire.SqlServer": "1.6.4",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
        "Microsoft.AspNetCore.Authentication.Facebook": "1.0.0",
        "Microsoft.AspNetCore.Authentication.Google": "1.0.0",
        "Hangfire.Autofac": "2.2.0"
    },
    "tools": {
        "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
        "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
        "Microsoft.DotNet.Watcher.Tools": "1.0.0-preview2-final",
        "Migrator.EF6.Tools": {
            "version": "1.0.1",
            "imports": "portable-net45+win8+dnxcore50"
        }
    },
    "frameworks": {
        "net46": {
            "dependencies": {
                "Authentication": {
                    "target": "project"
                },
                "Common": {
                    "target": "project"
                },
                "Domain": {
                    "target": "project"
                },
                "EFStorageProvider": {
                    "target": "project"
                },
                "Models": {
                    "target": "project"
                },
                "Services": {
                    "target": "project"
                }
            }

        }
    },
    "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
    },

    "runtimeOptions": {
        "configProperties": {
            "System.GC.Server": true
        }
    },

    "publishOptions": {
        "include": [
            ".babelrc",
            "appsettings.json",
            "App",
            "node_modules",
            "typings",
            "Views",
            "tsconfig.json",
            "tsd.json",
            "web.config",
            "webpack.*.js",
            "wwwroot"
        ]
    },

    "scripts": {
        "prepublish": [
            "npm install"
            // "node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js",
            // "node node_modules/webpack/bin/webpack.js"
        ],
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
    },

    "tooling": {
        "defaultNamespace": "WebUI"
    }
}
`

**Comment by ZombiesWithCoffee** [comment]
I don't see anything obvious yet.  You said that you had stdOutLog enabled, but you posted web.config with 

        stdoutLogEnabled="false"

**Comment by dcarl1** [comment]
Ah sorry about that, I've been pushing a ton to try and debug this. It was enabled, and it does create the stdOutLog files but they are completely empty. Trying with the runtime piece right now to see if it does anything.

**Comment by ZombiesWithCoffee** [comment]
A completely random untested shot in the dark...  Try fixing it like I fixed mine.  Replace

              "Microsoft.AspNetCore.Mvc": "1.0.1",

With

              "Microsoft.AspNetCore.Mvc": { "version": "1.0.1", "type": "platform" },

**Comment by dcarl1** [comment]
Good thought, but that seems to just break the public with a null reference error here:

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): Error : Object reference not set to an instance of an object.

`    <Publish
      RuntimeToolingDirectory ="$(SDKToolingDirectory)"
      ProjectFolder="$(MSBuildProjectDirectory)"
      Project="$(KPackWorkingDirectory)"
      Runtime="$(FinalPublishVersion)"
      WwwRoot="$(WebRoot)"
      WwwRootOut="$(WwwRootOut)"
      NoSource="$(NoSourceFlag)"
      Quiet="$(QuietFlag)"
      IncludeSymbols ="$(IncludeSymbolsFlag)"
      Native ="$(NativeFlag)"
      Configuration="$(PublishConfiguration)"
      Out="$(PublishOutputPathNoTrailingSlash)"
      ExternalToolsPath="$(ExternalToolsPath)"
      IsFilePreview="$(FilePreview)" 
      IISCommand="$(IISCommand)"
      SDKToolingIdentifier="$(SDKToolingIdentifier)"
      PublishFramework="$(PublishFramework)"
      PublishRuntime="$(PublishRuntime)"
      NoBuild="$(NoBuildFlag)"
      BuildOutDirectory ="$(BuildOutDirNoSlash)" 
      EnvironmentVariables="@(DnuPublishEnvironmentVariables)"/>`

Thanks for the help @ZombiesWithCoffee, but this issue seems to be related to net46 pretty heavily. I'm going to try rolling back to 1.0.0 for the time being and open a new ticket.

**Comment by moozzyk** [comment]
Did you check eventLog? Since stdoutLog is created I assume AspNetCoreModule is trying to do something so it should write failures to eventLog. Have you also tried running the application directly? - go to the folder where the application is published and try running it directly (I assume it will actually work - if it failed you would see something in the stdoutLog). Remember that IIS runs as a different user so it might be an issue with permissions.

**Comment by dcarl1** [comment]
@moozzyk Yep. See:

https://github.com/aspnet/IISIntegration/issues/270

It's Azure so I don't really have any permission options AFAIK.

**Comment by deadZedd** [comment]
I have the same 502.5 error (when using dotnet461), heres a repro:

File > new ASP.NET Core 1 > Empty project

Build > Publish > Azure with default settings > Outputs Hello world! correctly

Change project.json to contain:

```
 "frameworks": {
    "net461": {}
  },
```

And remove "Microsoft.NETCore.App" reference. (This is the same as starting a new blank Core 1 project on .Net Framework)

Build > Publish > Azure with default settings > Gives HTTP Error 502.5 - Process Failure

Enabling stdout logging shows this error on the azure platform: 
```

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.PlatformAbstractions.PlatformServices' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.AppContext, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.GetApplicationBasePath()
   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment..ctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices..ctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApplication15.Program.Main(String[] args) in MY PROJECT PATH/Program.cs:line 14
```

**Comment by ZombiesWithCoffee** [comment]
When publishing, do you have 'Remove additional files at destination' checked in the 'Settings' area of the publish window?

I literally went into my azure server and deleted every single assembly one at a time.  Was the only way I got around the 502.5 error.

**Comment by deadZedd** [comment]
@ZombiesWithCoffee ive tried with a checked "remove additional" files for all my slots with a clean core 1 project without luck. From you suggestion ive created a new webapp in azure and publishing to that works, so I obviously cant trust the "remove files" option. How did you clean you server? Via ftp?

**Comment by ZombiesWithCoffee** [comment]
I'm embarrassed to say that I went into 'Server Explorer' via Visual Studio and manually deleted the files one at a time.  It was therapeutic.  I'm positive that there is a much better way to do it.

**Comment by moozzyk** [comment]
I found that when you change frameworks in your project.json and republish the application to Azure (the same location/slot) the publish tool won't replace dlls at the target location if the names are the same. As a result you end up with stale dlls and you application won't work because after you have changed the framework it needs different versions. So yes, if you change the target framework you need to go to your Azure folder containing the old application and nuke all the dlls. I raised this issue with the tooling folks.
You can find more details in this thread: https://github.com/aspnet/Hosting/issues/801#issuecomment-227920473

**Comment by HADB** [comment]
Here's my problem and my solution:
Problems:
1. After upgrade Microsoft.NETCore.App to 1.0.1, I get 502.5 error when I use iis express.
2. Change Microsoft.NETCore.App to 1.0.0, everything is OK.
3. Publish to my server, both 1.0.1 and 1.0.0 are OK.

Solution:
Install [.NET Core 1.0.1 - VS 2015 Tooling Preview 2](https://go.microsoft.com/fwlink/?LinkID=827546) in my computer.

Now I can work with Microsoft.NETCore.App 1.0.1 using iis express.

**Comment by jakkaj** [comment]
Removing the files worked for me too - the problem occurs when you change target frameworks between publishes. 

You can easily delete all files using Kudu. Go to a CMD prompt, CD in to the wwwroot folder and type del /S * - that will delete all the old files :)

**Comment by asadsahi** [comment]
Thanks @jakkaj this trick worked for me too. I didn't even changed target framework, but was still having this problem during continuous deployments. Lets see how long this works now.

**Comment by jakkaj** [comment]
Perhaps differing versions on your dev machine to Azure?

**Comment by Uffman** [comment]
My problem:
Upgrade ASP.NET Core WebAPi to 1.1.0
If I publish to Azure from VS trough Publish action everything is OK.
If I user Visual Studio Team Service Build and Release I get HTTP Error 502.5 - Process Failure.
I found out the problem is in web.config.
When published trough Visual Studio:
`<aspNetCore processPath="dotnet" arguments=".\Cvetlicarna.Web.dll" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles\stdout" forwardWindowsAuthToken="false" />`
Publish from VSTS:
`<aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>`

If I manually change this line on Azure, page works fine.
Why isn't web.config changed by VSTS Build and Release process?

**Comment by moozzyk** [comment]
You are hitting a known issue where 1.1 runtime is not installed on VSTS agents. See this comment for resolution: https://github.com/aspnet/Hosting/issues/892#issuecomment-263407934

Same issue described here: https://github.com/aspnet/Home/issues/1842

/CC @muratg

**Comment by Uffman** [comment]
Tnx @moozzyk 
reverting to:
`"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"`
worked

**Comment by asadsahi** [comment]
Azure deployment happened successfully, but running app gives following error:

![image](https://cloud.githubusercontent.com/assets/3470892/20936079/230f9fce-bbd9-11e6-98c8-58bd8990fb70.png)

I haven't upgraded to new csproj yet and running using project.json with .net core 1.1 framework and targetting following sdk in global.json to force it to use this version:

```
{
    "projects": [
    ],
    "sdk": {
        "version": "1.0.0-preview2-1-003177"
    }
}
```

No idea what this error means. Anyone is aware of this issue?

**Comment by ZombiesWithCoffee** [comment]
That's the ONLY thing I could get with it.  After a week, I finally abandoned the full .NET Framework and trying to switch to core, and I am still down.

**Comment by dcarl1** [comment]
@asadsahi Turn on STDOUT logging and see if anything pops up in there, also check all the Azure logs. I've seen that happen before and its usually due to something crashing in the startup class.

**Comment by ZombiesWithCoffee** [comment]
Thanks for the reminder dcarl1.

Try this
            var webHost = new WebHostBuilder()
                .CaptureStartupErrors(true)
                .UseSetting("detailedErrors", "true")
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>();

            // For debugging startup errors

            webHost.CaptureStartupErrors(true);
            webHost.UseSetting("detailedErrors", "true");

            webHost.Build().Run();

**Comment by GuardRex** [comment]
The startup errors one is :sparkles: auto-magical :sparkles: ...

https://github.com/aspnet/IISIntegration/blob/e4cf12017b90a28379650987b58c3d77cdb2a5cb/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L49

**Comment by GuardRex** [comment]
[Sorry ... thought I pasted the wrong link there for a sec.]

The `CaptureStartupErrors()` is automatically done under `UseIISIntegration()` ...

https://github.com/aspnet/IISIntegration/blob/e4cf12017b90a28379650987b58c3d77cdb2a5cb/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L49

**Comment by dcarl1** [comment]
@ZombiesWithCoffee I should mention we are using the full .NET framework on Azure with 1.1 (xproj not csproj). Didn't really change anything other then package versions.

So far no issues. Deployment went out last night so we will see if those CGI errors show up again.

**Comment by ZombiesWithCoffee** [comment]
I'm extremely happy for you @dcarl1 !  I had absolutely no luck and eventually had to delete and recreate my app services.  And I'm still down!

@GuardRex, thanks for the update! I'll remove that from my startup code.

**Comment by dcarl1** [comment]
@ZombiesWithCoffee Post your project.json if you want, I can diff it with mine see if anything sticks out.

**Comment by ZombiesWithCoffee** [comment]
All I am getting at this time is the terribly generic error

       The specified CGI application encountered an error and the server terminated the process.

I believe that this problem is related to the issue, that publishing doesn't show the "Entity Framework Migrations" option.  Thanks for the offer to help though!

https://forums.asp.net/t/2111466.aspx?Publishing+doesn+t+show+the+Entity+Framework+Migrations+

http://stackoverflow.com/questions/41004824/asp-net-core-project-publish-doesnt-show-the-database-migrations-option

**Comment by dcarl1** [comment]
That error just means Kestrel has crashed (or timed out. I've seen it on super long requests). You might have to dig into the stdout and Azure logging but there should be another error somewhere. 

Unfortunately we use EF6 and an adapter and do all migrations through SQL so I can't help there :( Best of luck.

**Comment by asadsahi** [comment]
@dcarl1 @ZombiesWithCoffee , thanks for pointing out enabling the errors. My issue was a runtime error, which wasn't happening during dev or even in production build locally. Only when I was deploying to azure. Here is the code:

```
 services.AddDbContext<ApplicationDbContext>(options =>
            {
                string useSqLite = Configuration["Data:useSqLite"];
                if (useSqLite.ToLower() == "true")
                {
                    options.UseSqlite(Configuration["Data:SqlLiteConnectionString"]);
                }
                else
                {
                    options.UseSqlServer(Configuration["Data:SqlServerConnectionString"]);
                }

            });
```
So, I added UseSqlServer in options, but the "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",package wasn't added. So this was causing a runtime error, and only on Azure. Neither running locally or a production build was causing any issues.

**Comment by moozzyk** [comment]
See: https://github.com/aspnet/Home/issues/1842#issuecomment-265951372

**Comment by ricklove** [comment]
Wow, this killed my productivity for a whole day. This thread did not help me specifically, but it was the best one that I could find in searching. I wanted to leave my findings here in case others find it and need a different option:

I created a new project with VS and it published fine. So, I started copying files over to see if I could introduce the error. Nope, the new project published just fine to Azure with the same startup, project.json, web.config and all the content files.

Finally, I got WinMerge and found a few differences:

- SolutionFiles/global.json had a different SDK version, so I changed that to match new newer version
- PublishProfiles was different, so I deleted all my old publish profiles and started over

That fixed it!

**Comment by ZombiesWithCoffee** [comment]
I did the same thing @ricklove .  I finally had to break down for the 6th time and recreate the project from scratch to finally get it to work again.  So it's definitely not a code issue.

I wish my problem was a simple as the global.json file.  Mine are the same.

**Comment by ricklove** [comment]
Definitely a very frustrating experience after having no problems publishing with this project and then all of a sudden it blew up. It had been about a month since I had published with this project (but never had a problem with it) and I may have updated other projects and maybe the VS tooling or something.

The project was originally a RC2 project and is now at 1.0.1. I was just happy it worked and didn't bother trying to upgrade to the latest.

**Comment by nilavghosh** [comment]
I commented the sdk version from global.json in the solution and the deployment to azure started working fine.

```
{
  "projects": [ "src", "test" ]
  //,
  //"sdk": {
  //  "version": "1.0.0-preview2-003131"
  //}
}

```

**Comment by damccull** [comment]
Just an FYI for anyone finding this error. My problem causing it was because I use Kestrel with HTTPS in my startup and provide it a development key. That key doesn't exist on azure and never will, so it throws an exception. I solved it by the following technique:

```
    public class Program {
        public static void Main(string[] args) {
            var host = new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseStartup<Startup>();

            if (Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Development") {

                host.UseKestrel(options => {
                    var pfxFile = "kestrel-dev-cert.pfx";
                    options.UseHttps(pfxFile, "password");
                })
                .UseUrls("https://localhost:44348");
            } else {
                host.UseKestrel();
            }

            var hostbuilder = host.UseIISIntegration()
            .Build();

            hostbuilder.Run();
        }
    }
```

This allows me to run kestrel in https locally, but use IIS for https when deployed to Azure without throwing any missing file exceptions.

**Comment by assafY** [comment]
@nilavghosh you saved my life. Thanks.

**Comment by li2008kui** [comment]
问题解决了！
原因是升级.NET Core版本后引起的问题。
查看你的xxx.runtimeconfig.json文件
```{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.1.2" <-- (1.1.0 )此处改为安装版本即可
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
}

**Comment by mikebridge** [comment]
I'm getting this error too in a `.NETCoreApp 1.1` application deployed to an App Service on Azure , and I've enabled every debugging thing I can find and I still can't see what's going on.  This was working until I redeployed it.

After executing `dotnet publish` I edited this line in "web.config":
    <aspNetCore processPath="dotnet" arguments=".\Api.dll" stdoutLogEnabled="true" stdoutLogFile="%home%\LogFiles\dotnetcore" />

After uploading, the dotnetcore_*.log file shows me this:

```
Starting on http://0.0.0.0:5000
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:31657 on the IPv6 loopback interface.
System.AggregateException: One or more errors occurred. (Error -4090 EADDRNOTAVAIL address not available) ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4090 EADDRNOTAVAIL address not available
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)<---

Hosting environment: Production
Content root path: D:\home\site\wwwroot
Now listening on: http://localhost:31657
Application started. Press Ctrl+C to shut down.
```

Is this the problem or is it just a warning?  It says there's an error binding to port 31657 on IPv6, but at the end it's saying it is indeed listening on port 31657.

Other than that, I have several other directories under `/LogFiles`, but I've looked at all these and don't see anything that seems like an error:

```
/Application
/DetailedErrors
/http/RawLogs
/kudu/deployment
/kudu/trace
/SiteExtensions/Kudu
/W3SVC1142139096
ApplicationInsightsExtension.log
dotnetcore_10388_20177761539.log
eventlog.xml
```

The last event in EventLog.xml is:

```xml
<Event>
    <System>
        <Provider Name="IIS AspNetCore Module"/>
       <EventID>1001</EventID>
       <Level>0</Level>
       <Task>0</Task>
       <Keywords>Keywords</Keywords>
       <TimeCreated SystemTime="2017-07-07T06:15:47Z"/>
       <EventRecordID>1151159015</EventRecordID>
       <Channel>Application</Channel>
       <Computer>RD00155DFBE915</Computer>
       <Security/>
    </System>
    <EventData>
        <Data>Application 'MACHINE/WEBROOT/APPHOST/ZEPTAPI__7BE4' started process '6672' successfully and is listening on port '31657'.</Data>
    </EventData>
</Event>
```

Not sure what else to do.  

In the "Diagnose and solve problems" option, it says "Your app is healthy right now.".

**Comment by raRaRa** [comment]
@mikebridge I see this error for my apps as well. I don't think it's an actual issue. My apps are running fine on Azure with this initial error.

I would recommend adding more logging, e.g. in the Startup process to find out if something might be going on there.

**Comment by moozzyk** [comment]
EADDRNOTAVAIL for IPv6 on Azure is benign/informational and there are changes in 2.0 to not log the stack trace. See more details here: https://github.com/aspnet/KestrelHttpServer/issues/1001

**Comment by mikebridge** [comment]
@raRaRa & @moozzyk thanks, that at least eliminates some of the potential issues. 

I found this opaque error but no idea what it means:

```
Application 'MACHINE/WEBROOT/APPHOST/******' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline 'dotnet .\Api.dll', ErrorCode = '0x80004005 : 8000808c.
```

Maybe [this](https://stackoverflow.com/questions/43902658/asp-net-core-web-app-http-error-502-5-process-failure-on-visual-studio-15-2).  

Running `dotnet --info` from the azure portal console log gives me this:

```
> dotnet --info
D:\
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.2.9200
 OS Platform: Windows
 RID:         win8-x86
 Base Path:   D:\Program Files (x86)\dotnet\sdk\2.0.0-preview2-006497\
```

In development I'm running 1.0.4---is it using the wrong version of dotnet?  I don't see any way to select the version.

I really have no clue what to do here....

**Comment by mikebridge** [comment]
Ok, the issue is that I need to explicitly modify the reference in `.csproj` from `netcoreapp1.1` to `netcoreapp1.1.2`:
```
<TargetFramework>netcoreapp1.1.2</TargetFramework>
```
This seems to bring up the site with no errors.

**Comment by robertmclaws** [comment]
I'm experiencing the same issue in Azure on a ASP.NET Core 2.0 Preview 2 app, and this is the error I'm getting in STDOUT:
```
Error:
  An assembly specified in the application dependencies manifest (Accrue.Web.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Mvc.Razor.ViewCompilation', version: '2.0.0-preview2-final'
    path: 'lib/netcoreapp2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll'

  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-preview2-final-osx-x64.xml;aspnetcore-store-2.0.0-preview2-final-linux-x64.xml
```
First thing that jumps out is that this version was installed using a MacOS/Linux manifest, but I've confirmed that this running on Windows.

I should point out that my .csproj file shows: `<TargetFramework>netcoreapp2.0</TargetFramework>`

Any ideas?

**Comment by robertmclaws** [comment]
**UPDATE:** I solved the problem by setting my RuntimeIdentifier to the same runtime as my Azure Web App, (`<RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>`) and redeployed. This did a full XCOPY deployment to Azure, which executed just fine.

I'm not sure that this solves the core underlying issue in Azure, but at least my code is working.

As an aside, it seems obvious that VS2017.3 should detect your Azure settings, including what version of .NET Core is installed on the server, and wherever possible, automagically do what is necessary to get your app working. I will open some feedback to that effect on the VS portal and attempt to get it the proper visibility.

**Comment by davidebbo** [comment]
@robertmclaws some possibly related discussion on https://github.com/Azure/app-service-announcements-discussions/issues/2

**Comment by robertmclaws** [comment]
Thanks @davidebbo!

**Comment by robertmclaws** [comment]
Did this issue ever get fixed in production?

**Comment by davidebbo** [comment]
I don't remember all the details on this issue, but I think Azure production is fully deployed with all known fixes.

**Comment by jchadwick** [comment]
I'm running into this issue, too, although I'm trying to use the .NET Core 2.0 RTM (26423) bits.
Logs show this error:

> Error:
  An assembly specified in the application dependencies manifest (MyApp.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-rtm-26423-linux-x64.xml;aspnetcore-store-2.0.0-rtm-26423-osx-x64.xml;aspnetcore-store-2.0.0-rtm-26423-win7-x64.xml;aspnetcore-store-2.0.0-rtm-26423-win7-x86.xml

**Comment by Tratcher** [comment]
The 2.0 RTM Azure deployment has only just started. https://github.com/Azure/app-service-announcements-discussions/issues/6

**Comment by jchadwick** [comment]
Figured that was the case.  Thanks for the update - will watch that thread.

**Comment by wstllc** [comment]
Hi all,

Apologies up front, I am basically new to .NET. I read this discussion top to bottom, as I am encountering the same error message. Open to thoughts if anyone has any. Here is what I figured out in *my* situation. I have .NET Core 2.0 API. If I remove web.config and publish to Azure, the API works. Inside the web.config file in my project (yes, on recompile it reappears), I have 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" forwardWindowsAuthToken="false" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>

After banging my head against the wall for about a day, I realize now why the same API fails if I proceed to publish a second time. On the second pass (assuming I do not manually remove web.config first), the web.config file is edited (again, not by me, but by the compiler) and *now* looks like this:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="bin\IISSupport\VSIISExeLauncher.exe" arguments="-argFile IISExeLauncherArgs.txt" forwardWindowsAuthToken="false" stdoutLogEnabled="false" />
  </system.webServer>
</configuration>

At which point Azure throws our beloved error message.

If I remove web.config and start over, the API is happy (1st publish) and then sad (2nd publish) in reliable sequence.

What I can't figure out is what to do about it. I'm not the one putting two flavors of web.config together. The compiler is doing it.

Thoughts? Again, I'm very new to virtually *everything* start to finish... so there are a thousand things I might be doing wrong in my learn-everything never-done-this-before project.

**Comment by wstllc** [comment]
Hi all,

Apologies up front, I am basically new to .NET. I read this discussion top to bottom, as I am encountering the same error message. Open to thoughts if anyone has any. Here is what I figured out in *my* situation. I have .NET Core 2.0 API. If I remove web.config and publish to Azure, the API works. Inside the web.config file in my project (yes, on recompile it reappears), I have 
```

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" forwardWindowsAuthToken="false" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>

```
After banging my head against the wall for about a day, I realize now why the same API fails if I proceed to publish a second time. On the second pass (assuming I do not manually remove web.config first), the web.config file is edited (again, not by me, but by the compiler) and *now* looks like this:
```

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="bin\IISSupport\VSIISExeLauncher.exe" arguments="-argFile IISExeLauncherArgs.txt" forwardWindowsAuthToken="false" stdoutLogEnabled="false" />
  </system.webServer>
</configuration>
```

At which point Azure throws our beloved error message.

If I remove web.config and start over, the API is happy (1st publish) and then sad (2nd publish) in reliable sequence.

What I can't figure out is what to do about it. I'm not the one putting two flavors of web.config together. The compiler is doing it.

Thoughts? Again, I'm very new to virtually *everything* start to finish... so there are a thousand things I might be doing wrong in my learn-everything never-done-this-before project.

**Comment by Tratcher** [comment]
@wstllc Yeah, that looks like a tooling bug. Please report it to the tooling team via the VS "Send Feedback" tool.

**Comment by wstllc** [comment]
Thx for thoughts, Tratcher, but before I bother them, here's what I figured out. (Bug? Feature? I'm too new to know...)

What I worked out did not involve removing the web.config file, so let that thought be. In below comments, presume file remains and is never deleted.

It turns out that if I do the following steps, publishing will succeed:
1) Use IIS Express profile
2) *RUN* it locally first, and *THEN*
3) Publish to Azure

Guaranteed routes to failure:
Option #1: Use IIS profile, run app locally, then publish.
Option #2: Use IIS profile, switch back to IIS Express and publish without first running under the Express profile.

In short, the web.config version last used when the project runs locally is what gets published, regardless of which profile you happen to have selected at the moment.

What I don't myself understand is why IIS Express uses this (which works great when publishing to Azure)...

`
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" forwardWindowsAuthToken="false" stdoutLogEnabled="false" />
  </system.webServer>
</configuration>
`
...whereas IIS uses this (which is toxic to all API life forms on Azure)...

`
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="bin\IISSupport\VSIISExeLauncher.exe" arguments="-argFile IISExeLauncherArgs.txt" forwardWindowsAuthToken="false" stdoutLogEnabled="false" />
  </system.webServer>
</configuration>
`

Tratcher, if you think that's a bug in Visual Studio, I'll do as you suggest -- otherwise I'll chalk this all up "part of my learning curve."

Thanks!

**Comment by Tratcher** [comment]
Definitely a bug. You should never end up with VSIISExeLauncher in your process path after publish. Please report it to VS.

**Comment by wstllc** [comment]
Did so -- thx for feedback

**Comment by mihirdilip** [comment]
I came across the similar issue when I deployed asp.net core 2.0 on Azure. I fixed it by removing ` -argFile IISExeLauncherArgs.txt` from below 
```xml
<aspNetCore processPath="dotnet" arguments=".\xyz.dll -argFile IISExeLauncherArgs.txt" forwardWindowsAuthToken="false" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
```
so it looks like
```xml
<aspNetCore processPath="dotnet" arguments=".\xyz.dll" forwardWindowsAuthToken="false" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
```

I also tried by adding a dummy _IISExeLauncherArgs.txt_ file but it didn't work. Removing it worked for me. I hope this helps someone..

**Comment by davidebbo** [comment]
See related issue https://github.com/aspnet/websdk/issues/242

**Comment by mlawand** [comment]
i am facing the same issue, and i have tried all of the solutions in the thread but its not working.

i have a asp.net core 2.0 application which was working perfectly today it stopped suddenly and i am getting the issue 

502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

since my application was asp.net core 1.1 and i have updated it to 2.0 i deleted the wwwroot folder and reuploaded the application still it doesnt work.

the application works perfectly locally

this is the webconfig

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\xyzz.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>

Please any help to solve this

**Comment by guardrex** [comment]
@mlawand ... Can u paste in there the *web.config*, *Program.cs*, and *Startup.cs* (if you aren't using `WebHost` extensions for startup)? .... or put up a small GH repro project that we can see.

Also if you haven't seen it, we have an extensive troubleshooting section at: https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x#troubleshooting-tips

**Comment by mlawand** [comment]
@guardrex I have updated the post with web.config startup and program.cs i saw the link and went trough it

**Comment by guardrex** [comment]
ok ... let me run an :eye: eye over it and see if anything jumps out.

**Comment by mlawand** [comment]
@guardrex Thank you very much, i am hosting the application on Azure Web Apps With a standard S1 service plan

**Comment by guardrex** [comment]
Anything in the logging in the Azure Portal? I don't think they enable it automatically; you probably need to activate it in the portal for the Azure App. It should then light-up and provide logging that describes where/how the app is choking.

**Comment by mlawand** [comment]
@guardrex i updated the error log

**Comment by guardrex** [comment]
I'm so used to hosting ASP.NET Core apps now with VM's under full IIS that I'm not so familiar with the Azure Apps portal. You probably saw that down in the *Diagnostics Logs* area that they have several logging options. Of course, they don't match the phrase "stdout logging," so I'd be inclined to switch them all on for troubleshooting, then shut them all off afterward.

![capture](https://user-images.githubusercontent.com/1622880/31249838-751e00fa-a9de-11e7-95f5-bd4ac8c3563f.PNG)

**Comment by guardrex** [comment]
Next tab down is *Log stream*, and you should get *something* helpful there. You really just need the stdout logging piped through. It should give some indication what the app is choking on.

**Comment by guardrex** [comment]
Prob *Application Logging (Filesystem)* and *Detailed error messages* should do it.

**Comment by mlawand** [comment]
@guardrex i updated the original post with the stdout logging

**Comment by guardrex** [comment]
> Expression: [Recursive resource lookup bug]
> Description: Infinite recursion during resource lookup within System.Private.CoreLib. This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names. Resource name: ArgumentNull_Generic

Has a localization/culture 🐞 bug feeling to it. I'm not an expert in those areas (only dabble here and there when needed). Personally, I'd confirm that by disabling the code for localization. If the error goes away, then you know for sure that there's a problem there. Once you know for sure, I'd hit up the devs on Slack to see if anyone has some tips on troubleshooting the problem. Many devs there build localized apps. If you don't have access yet, the self-signup is here :point_right: http://tattoocoder.com/aspnet-slack-sign-up/

**Comment by mlawand** [comment]
@guardrex Thank you very much will sign up and ask there much appreciated

**Comment by razzemans** [comment]
I have the exact same error as @mlawand. I opened the issue here: https://github.com/dotnet/corefx/issues/24718

Also, after reverting to our .NET Core 1.2 version, I also get the same 502.5 error. Logs show:

```

Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Diagnostics.DiagnosticListener' threw an exception. ---> System.TypeLoadException: Could not load type 'System.Reflection.Assembly' from assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at __EnsureBootstrap__System.Diagnostics.DiagnosticSource.dll()
   at System.Diagnostics.DiagnosticListener..cctor()
   --- End of inner exception stack trace ---
   at System.Diagnostics.DiagnosticListener..ctor(String name)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Our.WebApplication.Program.Main(String[] args) in C:\projects\our-webapplication\src\Our.WebApplication\Program.cs:line 15
```

I cannot get this error fixed! Looks like the whole server is broken now. Help is appreciated.

**Comment by mlawand** [comment]
@razzemans please let me know if you find any solution for this issue

**Comment by razzemans** [comment]
@mlawand I fixed this by going to Kudu of my web app, clicking Site Extensions, and removing the Application Insights Extension.

**Comment by mlawand** [comment]
@razzemans i fixed my issue by creating a brand new application and migrating each part of the project to it. its a very lengthy process

**Comment by firemanwayne** [comment]
@damccull Your solution end a painful day and a half stent of moving to Https for me. His solution resolved my 502.5 error after publishing to Azure with .netcore2.0

**Comment by gcsuk** [comment]
I solved this issue by excluding web.config from my project.
This means that when publishing, it creates default files as VS thinks there is no web.config, so Azure is happy, whilst the web.config is still on disk and available to local IIS.

**Comment by tmmueller** [comment]
@razzemans Thank you! Removing the Application Insights extension worked for me as well. I removed it in the Azure portal rather than Kudu.

**Comment by yosbeleg89** [comment]
I have the same issue after upgrading to AspNetCore 2.0.6, I removed the wwwroot folder, excluded the web.config and still the same in Azure.

**Comment by guardrex** [comment]
@yosbeleg89 Did you run down the steps in the troubleshooting topic? https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-apps/troubleshoot

That's a fairly new topic, and I'd be happy to hear your feedback on if the steps outlined in the topic lead to uncovering the problem with your deployment.

**Comment by Tratcher** [comment]
The 2.0.6 deployment to Azure hasn't finished yet. See https://github.com/Azure/app-service-announcements/issues/92

**Comment by guardrex** [comment]
I wonder if it makes sense to deploy a new release to Azure first, then announce that the new release is available.

**Comment by davidebbo** [comment]
@guardrex unfortunately that's not really feasible. There is a bit of a chicken and egg problem, with things not fully working in Azure until the symbols are published by the Core team, and that doesn't happen until it's announced.

Deployment to App Service should normally be complete in a couple of days. You can test it now in West US 2 if you'd like.

That being said, I'm not sure that relates to the issue in this thread.
