### ISSUE TITLE
Can't install .NET Core Windows Server Hosting bundle (DotNetCore.1.0.5_1.1.2-WindowsHosting.exe) in windows server 2008 R2

### ISSUE THREAD

**Issue by KG1805** [aspnet/IISIntegration#403]
I tried to install the .NET Core Windows Server Hosting bundle on one of our windows server 2008 r2 servers. The install failed; I suspect it is because the server does not have access to the internet.

1. I already installed "vc_redist.x64.exe" (ver: 14.0.23026.0) still having issue to install.

2. windows server hosting is installed and I can view in the program and features

3. .net core run time cannot install. getting below error log.

[dd_DotNetCoreWinSvrHosting__20170721185409.log.docx](https://github.com/aspnet/IISIntegration/files/1169568/dd_DotNetCoreWinSvrHosting__20170721185409.log.docx)
![ins error](https://user-images.githubusercontent.com/30397423/28520206-2cb8bc72-70a1-11e7-83eb-f7bced87f23d.jpg)

[SERVER HOSTING ERROR.zip](https://github.com/aspnet/IISIntegration/files/1169592/SERVER.HOSTING.ERROR.zip)

I'd really appreciate some suggestions on how to proceed.

Thanks!
KG

**Comment by Tratcher** [comment]
@joeloff ?

**Comment by joeloff** [comment]
Thanks, I'll take a look at the logs and report back

**Comment by joeloff** [comment]
.It appears that the .NET Core runtime redist failed:

**[053C:073C][2017-07-21T18:54:50]i319: Applied execute package: DotNetRedistLts_x64, result: 0x80072ee7, restart: None**

@KG1805 there should be another log for the .NET Runtime installer that should have more details. The likely failure (without seeing the runtime log) is that the runtime will try to download the VC 14.x redist and if it doesn't have a connection it might fail.

Could you look for the .NET Runtime log and attach that file as well. The log for the runtime should also be in your %temp% folder.

**Comment by joeloff** [comment]
@KG1805 I noticed your comment from earlier about the VC redist. There was an issue around the time of VS2015 Update 3 RC where the copy of the redist that shipped with VS actually failed to write a registry key that's needed to detect if it's installed. What we've seen in a few instances is that .NET Core runtime installer would think that the redist is missing, when in fact a newer version is installed. When it applies an older version the installer would fail.

One thing to maybe try is to download a newer redist (14.0.24215.1), e.g http://go.microsoft.com/fwlink/?LinkID=615460&amp;clcid=0x409, install it and then repair the hosting bundle

**Comment by KG1805** [comment]
@joeloff I have attached the .NET runtime log and server hosting log. 
Please check.

[dd_DotNetCoreWinSvrHosting__20170721185409.log.docx](https://github.com/aspnet/IISIntegration/files/1172834/dd_DotNetCoreWinSvrHosting__20170721185409.log.docx)
[dd_DotNetCoreWinSvrHosting__20170721185409_000_AspNetCoreModule_x64.log.docx](https://github.com/aspnet/IISIntegration/files/1172836/dd_DotNetCoreWinSvrHosting__20170721185409_000_AspNetCoreModule_x64.log.docx)
[Microsoft_.NET_Core_1.0.5_-_Runtime_(x64)_20170721185439.log.docx](https://github.com/aspnet/IISIntegration/files/1172835/Microsoft_.NET_Core_1.0.5_-_Runtime_.x64._20170721185439.log.docx)

**Comment by joeloff** [comment]
@KG1805 Thanks for the logs. The .NET Runtime log confirms that it failed to download the required VC redist:

[1120:0624][2017-07-21T18:54:50]e000: Error 0x80072ee7: Failed attempt to download URL: 'https://download.microsoft.com/download/1/F/0/1F01DD22-748C-41A7-89DE-54D64355CDA6/vc_redist.x64.exe' to: 'C:\Users\ADMINI~1\AppData\Local\Temp\2\{1828EDAF-686E-4E7C-B48F-308C84597DCD}\VC_redist.x64.exe'
[1120:0624][2017-07-21T18:54:50]e000: Error 0x80072ee7: Failed to acquire payload from: 'https://download.microsoft.com/download/1/F/0/1F01DD22-748C-41A7-89DE-54D64355CDA6/vc_redist.x64.exe' to working path: 'C:\Users\ADMINI~1\AppData\Local\Temp\2\{1828EDAF-686E-4E7C-B48F-308C84597DCD}\VC_redist.x64.exe'

I'd suggest downloading the redist and then installing it manually before repairing the hosting bundle. In 2.0, .NET Core has removed the dependency on the VC redist, but for 1.x it's unfortunately required.

**Comment by KG1805** [comment]
1. After uninstalled all my old components (redist & serverhosting)
2.  Downloaded and Install redist (14.0.24215.1), e.g http://go.microsoft.com/fwlink/?LinkID=615460&amp;clcid=0x409
3. Install window server hosting (DotNetCore.1.0.5_1.1.2-WindowsHosting.exe)

My issues are resolved.  

@joeloff. Thank you for all your assistance.

**Comment by mmillican** [comment]
@joeloff 
> In 2.0, .NET Core has removed the dependency on the VC redist, but for 1.x it's unfortunately required.

I encountered this error while trying to install the 2.0 hosting bundle on a server which already had 1.1 installed.   I tried installing the VC redist, restarted the machine and still receiving the error.

I see this in my logs:

```
[06A8:0E5C][2017-09-08T11:51:23]i301: Applying execute package: dotnet_runtime_2.0.0_win_x86.msi, action: Install, path: C:\ProgramData\Package Cache\{45EC6F59-7976-4EE5-99A9-851D9BB8DE84}v16.0.25521\dotnet-runtime-2.0.0-win-x86.msi, arguments: ' ARPSYSTEMCOMPONENT="1" DOTNETHOME="C:\Program Files (x86)\dotnet"'
[06A8:0E5C][2017-09-08T11:51:24]e000: Error 0x80070643: Failed to install MSI package.
[06A8:0E5C][2017-09-08T11:51:24]e000: Error 0x80070643: Failed to execute MSI package.
[0960:07DC][2017-09-08T11:51:24]e000: Error 0x80070643: Failed to configure per-machine MSI package.
```

Any ideas?

**Comment by joeloff** [comment]
@mmillican There should be a separate log for the individual MSI that will contain more detail on the failure. The hosting bundle log usually just contains a summary of each package. Can you attach the MSI log? It should be in your %temp% folder

**Comment by mmillican** [comment]
@joeloff Ah, I found that and it pointed to my problem.  It's a disk space issue on one of the drives :|
